### ISSUE TITLE
Cashu Extension Upgrade Fails: lnbits.core.helpers:migrate_extension_database:22 | No module named 'bitcoin'

### ISSUE THREAD

**Issue by HamishMacEwan** [lnbits/cashu#46]
After upgrading to LNbits 0.11.1 attempts to upgrade the Cashu extension results in:

Failed to install extension cashu (0.3.1).
500 INTERNAL SERVER ERROR

The log reads as follows:
```
2023-10-17 21:31:01.76 | INFO | lnbits.extension_manager:download_archive:377 | Downloading extension cashu (0.3.0).
2023-10-17 21:31:02.78 | INFO | lnbits.extension_manager:extract_archive:402 | Extracting extension cashu (0.3.0).
2023-10-17 21:31:02.94 | SUCCESS | lnbits.extension_manager:extract_archive:439 | Extension Cashu (0.3.0) installed.
2023-10-17 21:31:03.08 | ERROR | lnbits.core.helpers:migrate_extension_database:22 | No module named 'bitcoin'
2023-10-17 21:31:03.08 | WARNING | lnbits.core.views.api:api_install_extension:814 | Please make sure that the extension `cashu` has a migrations file.
2023-10-17 21:31:03.11 | ERROR | lnbits.app:http_exception_handler:501 | HTTPException 500: Failed to install extension cashu (0.3.0).
```

**Comment by prusnak** [comment]
You are not installing 0.3.1 but 0.3.0 (see the logs you posted).

Try again but this time install 0.3.1

**Comment by HamishMacEwan** [comment]
Again:
```
LNbits version: 0.11.1
Failed to install extension cashu (0.3.1).
500 INTERNAL SERVER ERROR
```
But now the log reads:
```
2023-10-19 04:46:04.80 | INFO | lnbits.extension_manager:download_archive:377 | Downloading extension cashu (0.3.1).
2023-10-19 04:46:05.82 | INFO | lnbits.extension_manager:extract_archive:402 | Extracting extension cashu (0.3.1).
2023-10-19 04:46:05.93 | SUCCESS | lnbits.extension_manager:extract_archive:439 | Extension Cashu (0.3.1) installed.
2023-10-19 04:46:05.96 | ERROR | lnbits.core.helpers:migrate_extension_database:22 | cannot import name 'DLEQ' from 'lnbits.extensions.cashu.lib.cashu.core.base' (/app/lnbits/extensions/cashu/lib/cashu/core/base.py)
2023-10-19 04:46:05.96 | WARNING | lnbits.core.views.api:api_install_extension:814 | Please make sure that the extension `cashu` has a migrations file.
2023-10-19 04:46:05.98 | ERROR | lnbits.app:http_exception_handler:501 | HTTPException 500: Failed to install extension cashu (0.3.1).
```
I note that LNbits is prompting for a 0.2.6 update:
![image](https://github.com/lnbits/cashu/assets/388061/8c169360-ab86-445d-9bbb-77145f51cd60)
And that as a result of some testing with calle, an additional repository:

`LNBITS_EXTENSIONS_MANIFESTS="https://raw.githubusercontent.com/lnbits/lnbits-extensions/main/extensions.json,https://raw.githubusercontent.com/lnbits/cashu/main/manifest.json"
`
![image](https://github.com/lnbits/cashu/assets/388061/42181708-b418-4065-b83f-00a06704f04f)

**Comment by callebtc** [comment]
Happy to hear that the first error is gone. However, I don't understand how the second error comes about. The `DLEQ` class is clearly present in the file that is mentioned in the logs... 

Did you run `poetry install` after updating lnbits to 0.11.1?

**Comment by HamishMacEwan** [comment]
The code that updates LNbits in the myNodeBTC distribution is here: https://github.com/mynodebtc/mynode/blob/master/rootfs/standard/usr/bin/mynode_docker_images.sh#L186

But I note: `| ERROR | lnbits.core.helpers:migrate_extension_database:22 | cannot import name 'DLEQ' from 'lnbits.extensions.cashu.lib.cashu.core.base' (/app/lnbits/extensions/cashu/lib/cashu/core/base.py)`

The install is trying to load from the Docker filesystem rooted at `/app/` but there is no `lnbits` directory there, its contents are (outside Docker):

```
admin@flat6:/mnt/hdd/mynode/lnbits $ ls
database.sqlite3        ext_livestream.sqlite3   ext_scrub.sqlite3
ext_bleskomat.sqlite3   ext_lnaddress.sqlite3    ext_smtp.sqlite3
ext_boltcards.sqlite3   ext_lndhub.sqlite3       ext_splitpayments.sqlite3
ext_boltz.sqlite3       ext_lnticket.sqlite3     ext_streamalerts.sqlite3
ext_copilot.sqlite3     ext_lnurldevice.sqlite3  ext_subdomains.sqlite3
ext_deezy.sqlite3       ext_lnurlpos.sqlite3     ext_tipjar.sqlite3
ext_discordbot.sqlite3  ext_lnurlp.sqlite3       ext_tpos.sqlite3
extensions              ext_market.sqlite3       ext_usermanager.sqlite3
ext_events.sqlite3      ext_nostrclient.sqlite3  ext_watchonly.sqlite3
ext_example.sqlite3     ext_nostrnip5.sqlite3    ext_withdraw.sqlite3
ext_gerty.sqlite3       ext_offlineshop.sqlite3  logs
ext_hivemind.sqlite3    ext_paywall.sqlite3      unzip-temp
ext_invoices.sqlite3    ext_satsdice.sqlite3     zips
ext_jukebox.sqlite3     ext_satspay.sqlite3
```
The `extensions`  directory contains only zip files of extensions.

**Comment by HamishMacEwan** [comment]
Following calles advice in PM, "Can you try removing the custom manifest path that you've entered a while back and see if it works?"

![image](https://github.com/lnbits/cashu/assets/388061/3c5f8085-26a6-420c-be55-776ae0449e02)

Shutting down LNbits and copying back the `ext_cashu.sqlite3` from before this began has restored the mints too.
